name: Creepersday
description: Randomly, be invaded by creepers.
version: 1.7
author: arboriginal
website: http://dev.bukkit.org/server-mods/creepersday/
dev-url: https://github.com/arboriginal/Creepersday
main: me.arboriginal.Creepersday.Creepersday

commands:
    creepersday:
        description: Force starting/stopping a creepers' day
        usage: /creepersday <start/stop> [world_name (required in console)]
    
    creepersday-reload-config:
        description: Reload config files ("advanced" section values need a restart)
        usage: /creepersday-reload-config

permissions:
    creepersday.*:
        description: Gives access to all creepers'day commands
        children:
           creepersday.force: true
           creepersday.reload: true
    creepersday.force:
        description: Force starting/stopping a creepers' day
        default: op
    creepersday.reload:
        description: Update plugin config from files
        default: op
